### ISSUE TITLE
get_pokemon

### ISSUE THREAD

**Issue by MaestroMaelstrom** [PokeAPI/pokepy#62]
Hello,

hopefully this is helpful but it might be a simple mistake. I'm running through PyCharm for Windows.

Normally everything autofills for PyCharm which is true about the line pokepy.V2Client() but when I try to add .get_pokemon it highlights it and says, "Unresolved attribute reference 'get_pokemon' for class 'V2Client'" However the code does still run without errors.

![image](https://user-images.githubusercontent.com/31023793/95922172-af1fbd80-0d80-11eb-9a6d-fab770b25d49.png)
![image](https://user-images.githubusercontent.com/31023793/95922496-5b61a400-0d81-11eb-8d93-5ecc8e8e7537.png)

Not sure if this is fixable, or even a bug as I'm still lacking in a lot of coding skills and knowledge. My program is still in the very beginnings so excuse any horrid formatting.

Thanks,
MaestroMaelstrom

**Comment by Kronopt** [comment]
That's just because all 'get_' methods are generated when V2Client is instantiated.
So they don't actually exist when PyCharm tries to look for them.
I know those "unresolved references" don't look good on PyCharm, but if you follow the documentation it should be ok!
Any question feel free to ask them!
